export const caedoraClerkAppearance = {
  variables: {
    colorPrimary: 'var(--primary)',
    colorPrimaryForeground: 'var(--primary-foreground)',
    colorBackground: 'var(--popover)',
    colorForeground: 'var(--popover-foreground)',
    colorMuted: 'var(--muted)',
    colorMutedForeground: 'var(--muted-foreground)',
    colorInput: 'var(--background)',
    colorInputForeground: 'var(--foreground)',
    colorBorder: 'var(--border)',
    colorRing: 'var(--ring)',
    colorDanger: 'var(--destructive)',
    colorModalBackdrop: 'color-mix(in oklch, var(--background) 35%, transparent)',
    borderRadius: '0.5rem',
    fontFamily:
      'var(--font-geist-sans), ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  elements: {
    rootBox: 'caedora-clerk-root',
    cardBox: 'caedora-clerk-card-box',
    card: 'caedora-clerk-card',
    headerTitle: 'caedora-clerk-title',
    headerSubtitle: 'caedora-clerk-subtitle',
    formButtonPrimary: 'caedora-clerk-primary-button',
    formFieldInput: 'caedora-clerk-input',
    formFieldLabel: 'caedora-clerk-label',
    socialButtonsBlockButton: 'caedora-clerk-social-button',
    dividerLine: 'caedora-clerk-divider-line',
    dividerText: 'caedora-clerk-divider-text',
    footerActionLink: 'caedora-clerk-link',
    identityPreviewEditButton: 'caedora-clerk-link',
  },
} as const
